// Vita3K emulator project
// Copyright (C) 2026 Vita3K team

#include <vita3k_ios/NativeFrontend.h>
#include <vita3k_ios/PerformanceOptimizations.h>
#include <vita3k_ios/VirtualController.h>
#include <util/log.h>

// Apple's MacTypes.h declares `typedef char *Ptr;`, which collides with the
// emulator's global Ptr<T> template forward-declared by util/log.h above.
// Rename the MacTypes alias for the framework includes; nothing in this file
// uses it. MacTypes.h is fully included (and include-guarded) inside this
// region, so later transitive includes are no-ops.
#define Ptr MacTypesPtr
#import <AVFoundation/AVFoundation.h>
#import <GameController/GameController.h>
#import <QuartzCore/QuartzCore.h>
#import <UIKit/UIKit.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#import <objc/runtime.h>
#include <mach/mach.h>
#undef Ptr

#include <algorithm>
#include <atomic>
#include <cmath>
#include <mutex>
#include <utility>

#include "vita3k_ios/NativeFrontendInternal.h"
#import "vita3k_ios/TsubomiBridge.h"

// Generated by the Swift compiler from the @objc surface of the Swift sources;
// the name comes from PRODUCT_MODULE_NAME, pinned to "Tsubomi" in
// ios/CMakeLists.txt. This is how the remaining Objective-C++ screens reach
// the migrated SwiftUI ones.
#import "Tsubomi-Swift.h"

// The visible library is installed directly on the window instead of inside
// SDL's root controller. The presentation hook needs this reference so home
// sheets recess the library rather than the hidden Metal view below it.
static UIViewController *g_library_controller = nil;
// Edge constraints keep the hosting view's untransformed bounds matched to the
// window while modal depth temporarily scales it. Frame/autoresizing math uses
// the transformed frame during rotation and can leave the restored library
// larger than the portrait window.
static NSArray<NSLayoutConstraint *> *g_library_constraints = nil;

// iOS 26 no longer scales the presenting screen behind a sheet. Restore that
// depth cue for modal screens, while alerts and action-sheet confirmations dim
// in place without moving the library.
namespace {

const void *kTsubomiDepthBackgroundKey = &kTsubomiDepthBackgroundKey;
const void *kTsubomiDepthPresenterBackgroundKey = &kTsubomiDepthPresenterBackgroundKey;
const void *kTsubomiDepthTransformKey = &kTsubomiDepthTransformKey;
const void *kTsubomiDepthRadiusKey = &kTsubomiDepthRadiusKey;
const void *kTsubomiDepthMasksKey = &kTsubomiDepthMasksKey;
const void *kTsubomiDepthCurveKey = &kTsubomiDepthCurveKey;
const void *kTsubomiDepthShadeKey = &kTsubomiDepthShadeKey;
const void *kTsubomiDepthRestoringKey = &kTsubomiDepthRestoringKey;

BOOL should_add_modal_depth(UIViewController *controller) {
    return controller && ![controller isKindOfClass:UIAlertController.class];
}

UIView *modal_depth_background(UIViewController *presenter) {
    UIView *presenterView = presenter.viewIfLoaded;
    UIWindow *window = presenterView.window;
    UIView *library = g_library_controller.viewIfLoaded;
    if (window && presenter == window.rootViewController && library.window == window && !library.hidden)
        return library;
    return presenterView;
}

BOOL is_visible_library_background(UIView *view) {
    UIView *library = g_library_controller.viewIfLoaded;
    return view && view == library && library.window && !library.hidden;
}

void prepare_modal_depth(UIView *view) {
    if (!view || objc_getAssociatedObject(view, kTsubomiDepthTransformKey))
        return;
    objc_setAssociatedObject(view, kTsubomiDepthTransformKey,
        [NSValue valueWithCGAffineTransform:view.transform], OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    objc_setAssociatedObject(view, kTsubomiDepthRadiusKey,
        @(view.layer.cornerRadius), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    objc_setAssociatedObject(view, kTsubomiDepthMasksKey,
        @(view.layer.masksToBounds), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    objc_setAssociatedObject(view, kTsubomiDepthCurveKey,
        view.layer.cornerCurve, OBJC_ASSOCIATION_COPY_NONATOMIC);
    UIView *shade = [[UIView alloc] initWithFrame:view.bounds];
    shade.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    shade.backgroundColor = UIColor.blackColor;
    shade.alpha = 0;
    shade.userInteractionEnabled = NO;
    [view addSubview:shade];
    objc_setAssociatedObject(view, kTsubomiDepthShadeKey, shade, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

void apply_modal_depth(UIView *view) {
    NSValue *original = objc_getAssociatedObject(view, kTsubomiDepthTransformKey);
    if (!view || !original)
        return;
    view.transform = CGAffineTransformScale(original.CGAffineTransformValue, 0.92, 0.92);
    view.layer.cornerRadius = 28;
    view.layer.cornerCurve = kCACornerCurveContinuous;
    view.layer.masksToBounds = YES;
    UIView *shade = objc_getAssociatedObject(view, kTsubomiDepthShadeKey);
    shade.alpha = 0.22;
}

void animate_modal_depth(
    UIView *view, id<UIViewControllerTransitionCoordinator> coordinator) {
    if (!view)
        return;
    if (UIAccessibilityIsReduceMotionEnabled()) {
        apply_modal_depth(view);
        return;
    }
    if (coordinator) {
        // Coordinate in the stable container, not in the view whose transform
        // is changing. Using the recessed view as the transition coordinate
        // space briefly rebased its UIKit geometry and produced a one-frame
        // upward hop at the start of the sheet presentation.
        UIView *container = view.superview ?: view.window ?: view;
        const BOOL registered = [coordinator
            animateAlongsideTransitionInView:container
                                   animation:
                                       ^(__unused id<UIViewControllerTransitionCoordinatorContext> context) {
                                           apply_modal_depth(view);
                                       }
                                  completion:nil];
        if (registered)
            return;
    }
    [UIView animateWithDuration:0.5
                     delay:0
                   options:UIViewAnimationOptionBeginFromCurrentState
                       | UIViewAnimationOptionAllowUserInteraction
                       | UIViewAnimationOptionCurveEaseInOut
                animations:^{ apply_modal_depth(view); }
                completion:nil];
}

void restore_modal_depth(UIView *view, BOOL animated,
    id<UIViewControllerTransitionCoordinator> coordinator,
    dispatch_block_t didFinish) {
    if (!view) {
        if (didFinish)
            didFinish();
        return;
    }
    if ([objc_getAssociatedObject(view, kTsubomiDepthRestoringKey) boolValue]) {
        return;
    }
    NSValue *transform = objc_getAssociatedObject(view, kTsubomiDepthTransformKey);
    NSNumber *radius = objc_getAssociatedObject(view, kTsubomiDepthRadiusKey);
    NSNumber *masks = objc_getAssociatedObject(view, kTsubomiDepthMasksKey);
    NSString *curve = objc_getAssociatedObject(view, kTsubomiDepthCurveKey);
    UIView *shade = objc_getAssociatedObject(view, kTsubomiDepthShadeKey);
    if (!transform) {
        if (didFinish)
            didFinish();
        return;
    }
    objc_setAssociatedObject(
        view, kTsubomiDepthRestoringKey, @YES, OBJC_ASSOCIATION_RETAIN_NONATOMIC);

    void (^restore)(void) = ^{
        // Resolve any window-size change that occurred while the sheet was open
        // before removing the scale. With edge constraints this updates bounds
        // directly instead of deriving a new frame from the 92% transform.
        [view.superview layoutIfNeeded];
        view.transform = transform.CGAffineTransformValue;
        view.layer.cornerRadius = radius.doubleValue;
        shade.alpha = 0;
    };
    void (^cleanup)(void) = ^{
        // Keep clipping enabled until an interactive dismissal actually
        // finishes. masksToBounds is a Boolean and would otherwise snap off
        // on the first drag frame, making the still-rounded layer look square.
        view.layer.masksToBounds = masks.boolValue;
        view.layer.cornerCurve = curve;
        [shade removeFromSuperview];
        objc_setAssociatedObject(view, kTsubomiDepthTransformKey, nil, OBJC_ASSOCIATION_ASSIGN);
        objc_setAssociatedObject(view, kTsubomiDepthRadiusKey, nil, OBJC_ASSOCIATION_ASSIGN);
        objc_setAssociatedObject(view, kTsubomiDepthMasksKey, nil, OBJC_ASSOCIATION_ASSIGN);
        objc_setAssociatedObject(view, kTsubomiDepthCurveKey, nil, OBJC_ASSOCIATION_ASSIGN);
        objc_setAssociatedObject(view, kTsubomiDepthShadeKey, nil, OBJC_ASSOCIATION_ASSIGN);
        objc_setAssociatedObject(view, kTsubomiDepthRestoringKey, nil, OBJC_ASSOCIATION_ASSIGN);
        if (didFinish)
            didFinish();
    };
    if (animated && !UIAccessibilityIsReduceMotionEnabled()) {
        if (coordinator) {
            UIView *container = view.superview ?: view.window ?: view;
            const BOOL registered = [coordinator
                animateAlongsideTransitionInView:container
                                       animation:
                                           ^(__unused id<UIViewControllerTransitionCoordinatorContext> context) {
                                               restore();
                                           }
                                      completion:
                                          ^(id<UIViewControllerTransitionCoordinatorContext> context) {
                                              if (context.isCancelled) {
                                                  apply_modal_depth(view);
                                                  objc_setAssociatedObject(view,
                                                      kTsubomiDepthRestoringKey, nil,
                                                      OBJC_ASSOCIATION_ASSIGN);
                                              } else {
                                                  cleanup();
                                              }
                                          }];
            if (!registered) {
                [UIView animateWithDuration:0.5
                                 delay:0
                               options:UIViewAnimationOptionBeginFromCurrentState
                                   | UIViewAnimationOptionAllowUserInteraction
                                   | UIViewAnimationOptionCurveEaseInOut
                            animations:restore
                            completion:^(__unused BOOL finished) { cleanup(); }];
            }
        } else {
            [UIView animateWithDuration:0.5
                             delay:0
                           options:UIViewAnimationOptionBeginFromCurrentState
                               | UIViewAnimationOptionAllowUserInteraction
                               | UIViewAnimationOptionCurveEaseInOut
                        animations:restore
                        completion:^(__unused BOOL finished) { cleanup(); }];
        }
    } else {
        restore();
        cleanup();
    }
}

} // namespace

@interface UIViewController (TsubomiModalDepth)
- (void)tsubomi_presentViewController:(UIViewController *)controller
                             animated:(BOOL)animated
                           completion:(void (^)(void))completion;
- (void)tsubomi_dismissViewControllerAnimated:(BOOL)animated
                                    completion:(void (^)(void))completion;
- (void)tsubomi_viewWillAppear:(BOOL)animated;
@end

@implementation UIViewController (TsubomiModalDepth)

+ (void)load {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        Method present = class_getInstanceMethod(
            self, @selector(presentViewController:animated:completion:));
        Method depthPresent = class_getInstanceMethod(
            self, @selector(tsubomi_presentViewController:animated:completion:));
        method_exchangeImplementations(present, depthPresent);

        Method dismiss = class_getInstanceMethod(
            self, @selector(dismissViewControllerAnimated:completion:));
        Method depthDismiss = class_getInstanceMethod(
            self, @selector(tsubomi_dismissViewControllerAnimated:completion:));
        method_exchangeImplementations(dismiss, depthDismiss);

        Method appear = class_getInstanceMethod(self, @selector(viewWillAppear:));
        Method depthAppear = class_getInstanceMethod(self, @selector(tsubomi_viewWillAppear:));
        method_exchangeImplementations(appear, depthAppear);
    });
}

- (void)tsubomi_presentViewController:(UIViewController *)controller
                             animated:(BOOL)animated
                           completion:(void (^)(void))completion {
    UIView *background = modal_depth_background(self);
    const BOOL addsDepth = animated && is_visible_library_background(background)
        && should_add_modal_depth(controller)
        && !UIAccessibilityIsReduceMotionEnabled();
    if (addsDepth) {
        prepare_modal_depth(background);
        objc_setAssociatedObject(controller, kTsubomiDepthBackgroundKey,
            [NSValue valueWithNonretainedObject:background], OBJC_ASSOCIATION_RETAIN_NONATOMIC);
        objc_setAssociatedObject(self, kTsubomiDepthPresenterBackgroundKey,
            [NSValue valueWithNonretainedObject:background], OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
    [self tsubomi_presentViewController:controller animated:animated completion:completion];
    if (addsDepth)
        animate_modal_depth(background, controller.transitionCoordinator ?: self.transitionCoordinator);
}

- (void)tsubomi_dismissViewControllerAnimated:(BOOL)animated
                                    completion:(void (^)(void))completion {
    UIViewController *dismissed = self.presentedViewController ?: self;
    UIViewController *presenter = dismissed.presentingViewController;
    NSValue *stored = objc_getAssociatedObject(dismissed, kTsubomiDepthBackgroundKey);
    [self tsubomi_dismissViewControllerAnimated:animated completion:completion];
    restore_modal_depth(stored.nonretainedObjectValue, animated,
        dismissed.transitionCoordinator ?: self.transitionCoordinator, ^{
            objc_setAssociatedObject(
                dismissed, kTsubomiDepthBackgroundKey, nil, OBJC_ASSOCIATION_ASSIGN);
            objc_setAssociatedObject(
                presenter, kTsubomiDepthPresenterBackgroundKey, nil, OBJC_ASSOCIATION_ASSIGN);
        });
}

- (void)tsubomi_viewWillAppear:(BOOL)animated {
    [self tsubomi_viewWillAppear:animated];
    // Interactive sheet swipes do not necessarily call the public dismissal
    // method, but the presenting controller always reappears.
    NSValue *stored = objc_getAssociatedObject(self, kTsubomiDepthPresenterBackgroundKey);
    if (stored)
        restore_modal_depth(stored.nonretainedObjectValue, animated, self.transitionCoordinator, ^{
            objc_setAssociatedObject(
                self, kTsubomiDepthPresenterBackgroundKey, nil, OBJC_ASSOCIATION_ASSIGN);
        });
}

@end

namespace {

std::mutex g_action_mutex;
std::optional<Vita3KIOSFrontendAction> g_pending_action;

void queue_action(Vita3KIOSFrontendAction action) {
    const std::lock_guard lock(g_action_mutex);
    g_pending_action = std::move(action);
}

// Last snapshot the core reported, kept so the SwiftUI bridge can read it
// while the library view does not exist (during gameplay). The games vector
// also lets the bridge resolve a title id back to the fields the UI has no
// business knowing about - app_path and trophy_id.
std::mutex g_settings_mutex;
Vita3KIOSSettings g_last_settings;
std::vector<Vita3KIOSGameEntry> g_last_games;

void present_import_picker(BOOL firmware);
void present_license_picker();
void present_save_picker(NSString *titleId);
void present_library_archive_picker();
void reload_library_cells();

} // namespace

// Declared in NativeFrontend.mm's own scope rather than the anonymous
// namespace: -updateGames:settings: calls it from further down the file.
static void vita3k_ios_internal_cache_snapshot(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    const std::lock_guard lock(g_settings_mutex);
    g_last_settings = settings;
    g_last_games = games;
}

// Every observable piece of core state the SwiftUI frontend watches, pushed
// from one place.
//
// This exists because it was previously three separate calls spread across
// -updateGames:settings:, and the firmware push was lost when that method was
// deleted in the library migration - which left onboarding permanently stuck,
// since its per-page gating is exactly what FirmwareState feeds. Keeping the
// three together means a future caller cannot update one and forget another.
static void publish_core_snapshot(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    vita3k_ios_internal_cache_snapshot(games, settings);
    [TsubomiLibraryStateBridge updateWithGames:vita3k_ios_internal::bridge_games()
                                      settings:vita3k_ios_internal::bridge_settings()];
    [TsubomiFirmwareStateBridge updateWithPreinstalledReady:settings.preinstalled_package_ready
                                                  fontReady:settings.font_package_ready
                                          mainFirmwareReady:settings.main_firmware_ready
                                                   allReady:settings.firmware_ready];
}

static void set_metal_drawables_hidden(UIWindow *window, BOOL hidden);

namespace {

UIWindow *active_window() {
    UIWindow *fallback = nil;
    for (UIScene *scene in UIApplication.sharedApplication.connectedScenes) {
        if (![scene isKindOfClass:UIWindowScene.class]
            || scene.activationState == UISceneActivationStateUnattached)
            continue;
        for (UIWindow *window in ((UIWindowScene *)scene).windows) {
            if (window.isKeyWindow)
                return window;
            if (!fallback)
                fallback = window;
        }
    }
    // Session teardown can briefly leave no key window; the library must still
    // find a home instead of silently not appearing (black screen after quit).
    return fallback;
}

NSString *const kTsubomiOrientationLockKey = @"tsubomi.orientationLock";
NSString *const kTsubomiOrientationLockEnabledKey = @"tsubomi.orientationLockEnabled";
BOOL g_orientation_policy_installed = NO;
IMP g_sdl_supported_orientations = nullptr;

BOOL orientation_lock_enabled() {
    return [NSUserDefaults.standardUserDefaults
        boolForKey:kTsubomiOrientationLockEnabledKey];
}

UIInterfaceOrientationMask orientation_lock_mask() {
    NSString *value =
        [NSUserDefaults.standardUserDefaults stringForKey:kTsubomiOrientationLockKey]
        ?: @"portrait";
    if ([value isEqualToString:@"landscape"])
        return UIInterfaceOrientationMaskLandscapeRight;
    if ([value isEqualToString:@"landscapeFlipped"])
        return UIInterfaceOrientationMaskLandscapeLeft;
    return UIInterfaceOrientationMaskPortrait;
}

UIInterfaceOrientationMask tsubomi_sdl_supported_orientations(
    id controller, SEL command) {
    if (orientation_lock_enabled())
        return orientation_lock_mask();
    if (g_sdl_supported_orientations) {
        using SupportedOrientations = UIInterfaceOrientationMask (*)(id, SEL);
        return reinterpret_cast<SupportedOrientations>(
            g_sdl_supported_orientations)(controller, command);
    }
    return UIInterfaceOrientationMaskAllButUpsideDown;
}

void invalidate_orientation_policy(UIViewController *controller) {
    if (!controller)
        return;
    [controller setNeedsUpdateOfSupportedInterfaceOrientations];
    for (UIViewController *child in controller.childViewControllers)
        invalidate_orientation_policy(child);
    invalidate_orientation_policy(controller.presentedViewController);
}

void perform_on_main(dispatch_block_t block) {
    if (NSThread.isMainThread)
        block();
    else
        dispatch_async(dispatch_get_main_queue(), block);
}

void present_alert(NSString *title, NSString *message) {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    UIAlertController *alert = [UIAlertController alertControllerWithTitle:title
                                                                  message:message
                                                           preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];
    [root presentViewController:alert animated:YES completion:nil];
}

// Per-title display-name override (a frontend-only rename), keyed by title id.
NSString *title_override_key(NSString *identifier) {
    return [@"tsubomi.title_override." stringByAppendingString:identifier ?: @""];
}

NSString *display_title(NSString *identifier, NSString *original) {
    NSString *override = [NSUserDefaults.standardUserDefaults stringForKey:title_override_key(identifier)];
    return override.length ? override : original;
}

// The library metadata visibility toggles (title IDs, version, size) are read
// directly by the SwiftUI cells through @AppStorage - see DefaultsKey in
// DefaultsToggle.swift, which pins the same keys and the same default-ON
// behaviour. Nothing on this side reads them any more.

// Untinted Regular glass. Apple's guidance is to tint the *primary action*
// only — a global wash applied to every surface flattens the hierarchy and
// fights the material's own adaptive tinting, so the former white/black wash
// is gone.
//
// Both variants are cached: UIGlassEffect instances are immutable once
// configured and a UIVisualEffectView rebuilds its whole backdrop when -effect
// is assigned, so handing out a fresh object per call made cell reuse pay for
// a full effect teardown on every dequeue.
UIVisualEffect *glass_effect(const BOOL interactive = YES) {
    if (@available(iOS 26.0, *)) {
        static UIGlassEffect *live = nil;
        static UIGlassEffect *stat = nil;
        static dispatch_once_t once;
        dispatch_once(&once, ^{
            live = [UIGlassEffect effectWithStyle:UIGlassEffectStyleRegular];
            live.interactive = YES;
            stat = [UIGlassEffect effectWithStyle:UIGlassEffectStyleRegular];
            stat.interactive = NO;
        });
        return interactive ? live : stat;
    }
    return [UIBlurEffect effectWithStyle:UIBlurEffectStyleSystemMaterial];
}

// Whether surfaces drawn over a running game still use Liquid Glass.
//
// Mirrors DefaultsKey.liquidGlassInGame on the Swift side, including its
// default: an absent key means the material is on, so a missing value must not
// read as NO the way -boolForKey: would.
BOOL in_game_liquid_glass_enabled() {
    NSNumber *value = [NSUserDefaults.standardUserDefaults objectForKey:@"tsubomi.liquidGlassInGame"];
    return value == nil ? YES : value.boolValue;
}

// Liquid Glass shapes use continuous ("squircle") corners, not circular arcs.
// Every rounded surface in the app goes through here so the curvature matches
// the system's own glass containers.
void round_continuous(UIView *view, const CGFloat radius) {
    view.layer.cornerRadius = radius;
    view.layer.cornerCurve = kCACornerCurveContinuous;
}

// ---- Cover art cache --------------------------------------------------------
// Cells used to call -imageWithContentsOfFile: on every dequeue, so scrolling
// the library re-read and re-decoded a PNG per cell per frame on the main
// thread — the app's main source of scroll jank and of CPU wake-ups while
// simply browsing. Decode once off-main, keep the decoded bitmap in an NSCache
// (the system evicts it under pressure), and hand cells the ready image.

NSCache<NSString *, UIImage *> *cover_cache() {
    static NSCache<NSString *, UIImage *> *cache = nil;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        cache = [[NSCache alloc] init];
        cache.countLimit = 240;
        // Evict on memory warnings rather than competing with the emulator's
        // guest allocations.
        [NSNotificationCenter.defaultCenter
            addObserverForName:UIApplicationDidReceiveMemoryWarningNotification
                        object:nil
                         queue:NSOperationQueue.mainQueue
                    usingBlock:^(__unused NSNotification *note) {
                [cache removeAllObjects];
                // Defer Vulkan destruction to the render thread. UIKit's memory
                // warning callback must never tear down GPU objects concurrently.
                vita3k_ios::MemoryMonitor::request_gc();
            }];
    });
    return cache;
}

void invalidate_cover_cache(NSString *path) {
    if (path.length)
        [cover_cache() removeObjectForKey:path];
    else
        [cover_cache() removeAllObjects];
}

// Cached decode. Returns the image immediately when it is already resident;
// otherwise decodes on a background queue and invokes `ready` on the main
// thread. `ready` is not called when the image was returned synchronously.
UIImage *cover_image(NSString *path, void (^ready)(UIImage *)) {
    if (!path.length)
        return nil;
    if (UIImage *cached = [cover_cache() objectForKey:path])
        return cached;
    static dispatch_queue_t queue = nil;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        queue = dispatch_queue_create("tsubomi.covers", DISPATCH_QUEUE_SERIAL);
    });
    NSString *key = [path copy];
    dispatch_async(queue, ^{
        UIImage *image = [UIImage imageWithContentsOfFile:key];
        // Force the decode here instead of on the first draw, which is what
        // actually stalls the render loop mid-scroll.
        if (image)
            image = [image imageByPreparingForDisplay] ?: image;
        if (!image) {
            LOG_ERROR("iOS library art could not be decoded at '{}'", key.UTF8String);
            // Still report completion: callers that bridge this to an async
            // await would otherwise never resume. Callers keep their
            // placeholder by ignoring a nil result.
            dispatch_async(dispatch_get_main_queue(), ^{
                if (ready)
                    ready(nil);
            });
            return;
        }
        [cover_cache() setObject:image forKey:key];
        dispatch_async(dispatch_get_main_queue(), ^{
            if (ready)
                ready(image);
        });
    });
    return nil;
}

// ---- Per-game settings ------------------------------------------------------
// Overrides are a defaults dictionary per title; absent = use global settings.

NSString *game_settings_key(NSString *titleId) {
    return [@"tsubomi.gameSettings." stringByAppendingString:titleId ?: @""];
}

BOOL has_game_settings(NSString *titleId) {
    return [NSUserDefaults.standardUserDefaults dictionaryForKey:game_settings_key(titleId)] != nil;
}

Vita3KIOSSettings game_settings_or(NSString *titleId, const Vita3KIOSSettings &fallback) {
    NSDictionary *stored = [NSUserDefaults.standardUserDefaults dictionaryForKey:game_settings_key(titleId)];
    if (!stored)
        return fallback;
    Vita3KIOSSettings settings = fallback;
    if (stored[@"resolution"])
        settings.resolution_multiplier = [stored[@"resolution"] floatValue];
    if (stored[@"vsync"])
        settings.v_sync = [stored[@"vsync"] boolValue];
    if (stored[@"shader_cache"])
        settings.shader_cache = [stored[@"shader_cache"] boolValue];
    settings.fps_limit = 60;
    if (stored[@"fpsHack"])
        settings.fps_hack = [stored[@"fpsHack"] boolValue];
    if (stored[@"modulesMode"])
        settings.modules_mode = [stored[@"modulesMode"] intValue];
    if (stored[@"audioVolume"])
        settings.audio_volume = [stored[@"audioVolume"] intValue];
    if (stored[@"textureCache"])
        settings.texture_cache = [stored[@"textureCache"] boolValue];
    if ([stored[@"lleModules"] isKindOfClass:NSArray.class]) {
        settings.lle_modules.clear();
        for (id name in stored[@"lleModules"])
            if ([name isKindOfClass:NSString.class])
                settings.lle_modules.emplace_back([(NSString *)name UTF8String]);
    }
    if (stored[@"cpuOpt"])
        settings.cpu_opt = [stored[@"cpuOpt"] boolValue];
    if (stored[@"ngs"])
        settings.ngs_enable = [stored[@"ngs"] boolValue];
    if (stored[@"asyncPipelines"])
        settings.async_pipeline_compilation = [stored[@"asyncPipelines"] boolValue];
    if (stored[@"anisotropic"])
        settings.anisotropic_filtering = [stored[@"anisotropic"] intValue];
    if (stored[@"highAccuracy"])
        settings.high_accuracy = [stored[@"highAccuracy"] boolValue];
    if (stored[@"surfaceSync"])
        settings.surface_sync = [stored[@"surfaceSync"] boolValue];
    // Absent for titles last saved before the switch existed; those fall back
    // to the global value carried in `fallback`.
    if (stored[@"doubleBuffer"])
        settings.double_buffer = [stored[@"doubleBuffer"] boolValue];
    return settings;
}

void store_game_settings(NSString *titleId, const Vita3KIOSSettings &settings) {
    NSMutableArray<NSString *> *modules = [NSMutableArray array];
    for (const auto &name : settings.lle_modules)
        [modules addObject:[NSString stringWithUTF8String:name.c_str()]];
    [NSUserDefaults.standardUserDefaults setObject:@{
        @"resolution": @(settings.resolution_multiplier),
        @"vsync": @(settings.v_sync),
        @"shader_cache": @(settings.shader_cache),
        @"fpsHack": @(settings.fps_hack),
        @"modulesMode": @(settings.modules_mode),
        @"audioVolume": @(settings.audio_volume),
        @"textureCache": @(settings.texture_cache),
        @"lleModules": modules,
        @"cpuOpt": @(settings.cpu_opt),
        @"ngs": @(settings.ngs_enable),
        @"asyncPipelines": @(settings.async_pipeline_compilation),
        @"anisotropic": @(settings.anisotropic_filtering),
        @"highAccuracy": @(settings.high_accuracy),
        @"surfaceSync": @(settings.surface_sync),
        @"doubleBuffer": @(settings.double_buffer),
    } forKey:game_settings_key(titleId)];
}

} // namespace

void vita3k_ios_install_orientation_policy() {
    if (g_orientation_policy_installed)
        return;

    // SDL's iOS root controller implements this method itself, so changing
    // UIViewController's base implementation would never reach it. Replace
    // only SDL's implementation and leave every SwiftUI/UIKit modal alone.
    Class controllerClass = NSClassFromString(@"SDL_uikitviewcontroller");
    Method supported = class_getInstanceMethod(
        controllerClass, @selector(supportedInterfaceOrientations));
    if (!controllerClass || !supported) {
        LOG_ERROR("Could not install iOS orientation policy: SDL root controller is unavailable");
        return;
    }
    g_sdl_supported_orientations = method_setImplementation(
        supported, reinterpret_cast<IMP>(tsubomi_sdl_supported_orientations));
    g_orientation_policy_installed = YES;
}

void vita3k_ios_apply_orientation_lock() {
    perform_on_main(^{
        vita3k_ios_install_orientation_policy();
        UIWindow *window = active_window();
        UIWindowScene *scene = window.windowScene;
        if (!window || !scene)
            return;

        invalidate_orientation_policy(window.rootViewController);
        const UIInterfaceOrientationMask mask = orientation_lock_enabled()
            ? orientation_lock_mask()
            : window.rootViewController.supportedInterfaceOrientations;
        UIWindowSceneGeometryPreferencesIOS *preferences =
            [[UIWindowSceneGeometryPreferencesIOS alloc] initWithInterfaceOrientations:mask];
        [scene requestGeometryUpdateWithPreferences:preferences
                                      errorHandler:^(NSError *error) {
                                          LOG_WARN("iOS orientation request was declined: {}",
                                              error.localizedDescription.UTF8String
                                                  ?: "unknown UIKit error");
                                      }];
    });
}

namespace {
// Defined further down the file, past this block.
std::string hex_bytes(const std::string &value);
} // namespace
// The seam TsubomiBridge.mm uses; see NativeFrontendInternal.h. Thin
// forwarders so the storage details above stay file-local.
namespace vita3k_ios_internal {

void queue_frontend_action(Vita3KIOSFrontendAction action) {
    queue_action(std::move(action));
}

Vita3KIOSSettings current_global_settings() {
    const std::lock_guard lock(g_settings_mutex);
    return g_last_settings;
}

Vita3KIOSSettings load_title_settings(NSString *title_id, const Vita3KIOSSettings &fallback) {
    return game_settings_or(title_id, fallback);
}

void store_title_settings(NSString *title_id, const Vita3KIOSSettings &settings) {
    store_game_settings(title_id, settings);
}

void clear_title_settings(NSString *title_id) {
    [NSUserDefaults.standardUserDefaults removeObjectForKey:game_settings_key(title_id)];
}

UIImage *cached_art(NSString *path, void (^ready)(UIImage *)) {
    return cover_image(path, ready);
}

void present_firmware_picker() {
    present_import_picker(YES);
}

void reload_library() {
    reload_library_cells();
}

NSString *display_title_for(NSString *title_id, NSString *original) {
    return display_title(title_id, original);
}

void set_display_title(NSString *title_id, NSString *title) {
    NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
    // An empty rename clears the override so the packaged title returns.
    if (title.length)
        [defaults setObject:title forKey:title_override_key(title_id)];
    else
        [defaults removeObjectForKey:title_override_key(title_id)];
}

bool title_has_settings(NSString *title_id) {
    return has_game_settings(title_id);
}

std::string hex_bytes_for_log(const std::string &value) {
    return hex_bytes(value);
}

std::vector<Vita3KIOSGameEntry> current_games() {
    const std::lock_guard lock(g_settings_mutex);
    return g_last_games;
}

std::optional<Vita3KIOSGameEntry> game_for_title(NSString *title_id) {
    const std::string wanted = title_id.UTF8String ? title_id.UTF8String : "";
    const std::lock_guard lock(g_settings_mutex);
    for (const auto &game : g_last_games) {
        if (game.title_id == wanted)
            return game;
    }
    return std::nullopt;
}

void present_game_picker() {
    present_import_picker(NO);
}

void present_license_import_picker() {
    present_license_picker();
}

void present_save_import_picker(NSString *title_id) {
    present_save_picker(title_id);
}

// Settings closes itself before asking for one of these pickers, so that the
// install progress drawn on the library behind it is visible. UIKit drops a
// presentation aimed at a controller that is still dismissing, so wait for the
// sheet to finish leaving rather than racing it. The wait is bounded: if
// something else is genuinely on screen, present over it as before instead of
// silently doing nothing.
void present_after_sheet_dismissal(void (^present)(void), int attempts_left = 40) {
    UIViewController *root = active_window().rootViewController;
    if (root.presentedViewController && attempts_left > 0) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.05 * NSEC_PER_SEC)),
            dispatch_get_main_queue(), ^{
                present_after_sheet_dismissal(present, attempts_left - 1);
            });
        return;
    }
    present();
}

void present_all_save_import_picker() {
    present_after_sheet_dismissal(^{
        present_save_picker(@"");
    });
}

void present_library_archive_import_picker() {
    present_after_sheet_dismissal(^{
        present_library_archive_picker();
    });
}

bool firmware_ready_or_alert() {
    const auto settings = current_global_settings();
    if (settings.firmware_ready)
        return true;
    NSString *missing = [NSString stringWithUTF8String:settings.missing_firmware.c_str()]
        ?: @"required firmware";
    present_alert(@"Complete firmware setup",
        [NSString stringWithFormat:
            @"Install PSVUPDAT.PUP and PSP2UPDAT.PUP (fonts) before importing or playing games.\n\nMissing: %@\n\nUse + > Import firmware (.PUP).",
            missing]);
    return false;
}

void present_settings_sheet(NSString *title_id, NSString *display_name) {
    UIViewController *root = active_window().rootViewController;
    if (!root || root.presentedViewController)
        return;
    [TsubomiSoundEffects playNamed:@"loading"];
    // Belt and braces: a lingering game drawable must never be visible under
    // the settings sheet.
    set_metal_drawables_hidden(active_window(), YES);
    UIViewController *controller = title_id.length
        ? [TsubomiSettingsHost settingsViewControllerForTitle:title_id
                                                  displayName:display_name
                                               dismissHandler:^{}]
        : [TsubomiSettingsHost globalSettingsViewControllerWithDismissHandler:^{
              // The core applies the change on its own thread and reports
              // restart-required fields through the status toast.
              Vita3KIOSFrontendAction action;
              action.kind = Vita3KIOSFrontendActionKind::Refresh;
              queue_action(std::move(action));
          }];
    [root presentViewController:controller animated:YES completion:nil];
}

void show_jit_required_alert() {
    UIViewController *root = active_window().rootViewController;
    while (root.presentedViewController)
        root = root.presentedViewController;
    if (root)
        [root presentViewController:[TsubomiJITHost viewController] animated:YES completion:nil];
}

void show_graphics_help() {
    present_alert(@"Graphics help",
        @"If a game's shaders or textures do not look correct, open that game's settings and try Graphics > High accuracy. "
        @"If lighting appears white or missing, also enable Graphics > Surface sync. "
        @"If character models look shattered or garbled, make sure Graphics > Double buffer is off.");
}

void invalidate_cached_art(NSString *path) {
    invalidate_cover_cache(path);
}

} // namespace vita3k_ios_internal

namespace {

std::string hex_bytes(const std::string &value) {
    constexpr char digits[] = "0123456789ABCDEF";
    std::string result;
    result.reserve(value.size() * 3);
    for (const unsigned char byte : value) {
        if (!result.empty())
            result.push_back(' ');
        result.push_back(digits[byte >> 4]);
        result.push_back(digits[byte & 0x0F]);
    }
    return result;
}

} // namespace

// The SwiftUI library (TsubomiLibraryHost). Retained here because only its
// view is installed in the hierarchy; its content comes from LibraryState,
// which the core pushes into through TsubomiLibraryStateBridge.
// Onboarding is added over the library's view, so it is retained alongside it.
static UIViewController *g_onboarding_controller = nil;

static void remove_onboarding_view() {
    [g_onboarding_controller beginAppearanceTransition:NO animated:NO];
    [g_onboarding_controller.view removeFromSuperview];
    [g_onboarding_controller endAppearanceTransition];
    g_onboarding_controller = nil;
}

// Convenience for the many call sites that only want the library's view.
static UIView *library_view() {
    return g_library_controller.view;
}

static void attach_library_view(UIView *host) {
    UIView *library = library_view();
    if (!library || !host)
        return;
    if (library.superview == host && g_library_constraints.count)
        return;

    [NSLayoutConstraint deactivateConstraints:g_library_constraints ?: @[]];
    g_library_constraints = nil;
    [library removeFromSuperview];
    library.translatesAutoresizingMaskIntoConstraints = NO;
    [host addSubview:library];
    g_library_constraints = @[
        [library.leadingAnchor constraintEqualToAnchor:host.leadingAnchor],
        [library.trailingAnchor constraintEqualToAnchor:host.trailingAnchor],
        [library.topAnchor constraintEqualToAnchor:host.topAnchor],
        [library.bottomAnchor constraintEqualToAnchor:host.bottomAnchor],
    ];
    [NSLayoutConstraint activateConstraints:g_library_constraints];
}
// Last-known JIT availability, applied whenever the library is (re)shown so the
// banner is correct even across library rebuilds between game sessions.
static BOOL g_jit_available = NO;
// A quit game's SDL/Metal drawable can be torn down over several runloop
// ticks, not just the one after vita3k_ios_show_library reasserts visibility
// - if settings gets opened (or the library redraws) in that window, the
// one-shot hide can miss a drawable that gets (re)added moments later,
// showing a frozen frame of the game that was just quit behind the UI.
// Re-run the hide pass on a short repeating timer for as long as the library
// is on screen instead of relying on a single reassertion.
static NSTimer *g_library_metal_hide_timer = nil;
// Set once the very first library presentation of this process has played its
// launch intro. Returning to the library after quitting a game recreates the
// controller too (vita3k_ios_hide_library nils it out), so this can't just be
// a null check or every game-to-library transition would replay the intro.
static BOOL g_app_launch_intro_shown = NO;

namespace {
void reload_library_cells() {
    // The library display toggles (title IDs, version, size) are read straight
    // from NSUserDefaults by the SwiftUI cells via @AppStorage, so those
    // re-render themselves. This re-derives the entries for the changes that
    // are not observable that way - a new custom cover, or a rename.
    [TsubomiLibraryStateBridge refreshEntries];
}
} // namespace


// Game-controller navigation for the native UI.
//
// This used to walk g_library's UIView subtree, collect focusable views, and
// move a focus ring spatially. The library is SwiftUI now and has no such
// subtree, so the navigator is reduced to what it should always have been: it
// reads the controller and forwards intent. LibraryState owns which game is
// focused and maps D-pad movement onto whichever presentation is showing (see
// LibraryState.FocusLayout); the view draws the ring and scrolls it into view.
//
// Handlers no-op whenever the library is off screen, so in-game input is never
// intercepted.
@interface Vita3KPadNavigator : NSObject
@property(nonatomic) BOOL active;
+ (instancetype)shared;
- (void)start;
- (void)stop;
@end

@implementation Vita3KPadNavigator

+ (instancetype)shared {
    static Vita3KPadNavigator *navigator;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        navigator = [[Vita3KPadNavigator alloc] init];
        [NSNotificationCenter.defaultCenter addObserverForName:GCControllerDidConnectNotification
                                                        object:nil
                                                         queue:NSOperationQueue.mainQueue
                                                    usingBlock:^(NSNotification *note) {
            [navigator wireController:note.object];
        }];
    });
    return navigator;
}

- (void)start {
    self.active = YES;
    for (GCController *controller in GCController.controllers)
        [self wireController:controller];
}

- (void)stop {
    self.active = NO;
    [TsubomiLibraryStateBridge clearFocus];
}

- (void)wireController:(GCController *)controller {
    GCExtendedGamepad *pad = controller.extendedGamepad;
    if (!pad)
        return;
    __weak Vita3KPadNavigator *weakSelf = self;
    pad.dpad.up.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:0 y:-1];
    };
    pad.dpad.down.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:0 y:1];
    };
    pad.dpad.left.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:-1 y:0];
    };
    pad.dpad.right.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf moveX:1 y:0];
    };
    pad.buttonA.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf activate];
    };
    pad.buttonB.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf back];
    };
    pad.buttonY.pressedChangedHandler = ^(__unused GCControllerButtonInput *b, __unused float v, BOOL pressed) {
        if (pressed) [weakSelf gameActions];
    };
    // L1/R1 cycled the old settings screen's categories. The SwiftUI settings
    // screen is one scrolling Form, so there is nothing to cycle; the handlers
    // are cleared rather than left pointing at a removed method.
    pad.leftShoulder.pressedChangedHandler = nil;
    pad.rightShoulder.pressedChangedHandler = nil;
}

// The library is driveable only while it is on screen and nothing is presented
// over it. A presented sheet (settings, trophies) is SwiftUI's to handle.
// Whatever the library currently has presented over it - a settings/trophy
// sheet, or the pad-actions / delete confirmation dialog. The library is
// parented to the window with no containment (see vita3k_ios_show_library), so
// SwiftUI presents from g_library_controller, not from window.rootViewController
// - checking only the latter let controller input keep driving the library
// behind an open context menu, so Cross booted a game instead of picking an
// item.
static UIViewController *library_presented_controller() {
    if (g_library_controller.presentedViewController)
        return g_library_controller.presentedViewController;
    return library_view().window.rootViewController.presentedViewController;
}

- (BOOL)navigationAllowed {
    return self.active
        && library_view().window != nil
        && library_presented_controller() == nil;
}

- (void)moveX:(NSInteger)dx y:(NSInteger)dy {
    if (![self navigationAllowed])
        return;
    [TsubomiLibraryStateBridge moveFocusByX:dx y:dy];
}

- (void)activate {
    if (![self navigationAllowed])
        return;
    [TsubomiLibraryStateBridge activateFocused];
}

- (void)gameActions {
    if (![self navigationAllowed])
        return;
    [TsubomiLibraryStateBridge showActionsForFocused];
}

- (void)back {
    if (!self.active)
        return;
    // Circle dismisses whatever the library has presented - including the
    // pad-actions dialog opened with Triangle - which is why this looks at the
    // library controller too, not only the window root.
    UIViewController *presented = library_presented_controller();
    if (presented) {
        [presented dismissViewControllerAnimated:YES completion:nil];
        return;
    }
    // Nothing presented: drop the focus ring so the library returns to its
    // touch-driven appearance.
    [TsubomiLibraryStateBridge clearFocus];
}

@end

// Presents the Files picker and hands a durable, app-owned copy to the
// emulator loop.
@interface Vita3KImportPicker : NSObject <UIDocumentPickerDelegate>
@property(nonatomic) Vita3KIOSFrontendActionKind kind;
@property(nonatomic, copy) NSString *titleId;
@end

@implementation Vita3KImportPicker

- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls {
    (void)controller;
    NSURL *url = urls.firstObject;
    if (!url)
        return;
    // Snapshot the delegate state before leaving the main thread. The picker
    // delegate is shared by every import surface and can be reconfigured for a
    // later picker while a large iCloud file is still being materialized.
    const Vita3KIOSFrontendActionKind kind = self.kind;
    NSString *titleId = [self.titleId copy];
    NSString *filename = url.lastPathComponent.length ? url.lastPathComponent : @"import.bin";

    NSString *preparing = kind == Vita3KIOSFrontendActionKind::ImportFirmware
        ? @"Preparing firmware…"
        : @"Preparing import…";
    [TsubomiLibraryStateBridge setBusyMessage:preparing];

    // File-provider reads can download hundreds of megabytes and are much
    // slower through compatibility containers such as LiveContainer. Keeping
    // that coordinated copy off the main thread prevents the selection from
    // looking ignored (or being killed by the main-thread watchdog).
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY, 0), ^{
        @autoreleasepool {
            NSFileManager *manager = NSFileManager.defaultManager;
            const BOOL scoped = [url startAccessingSecurityScopedResource];

            NSError *directoryError = nil;
            NSURL *documents = [manager URLForDirectory:NSDocumentDirectory
                                               inDomain:NSUserDomainMask
                                      appropriateForURL:nil
                                                 create:YES
                                                  error:&directoryError];
            NSURL *importDirectory = [[documents URLByAppendingPathComponent:@"Tsubomi"
                                                                  isDirectory:YES]
                URLByAppendingPathComponent:@"import" isDirectory:YES];
            if (documents) {
                [manager createDirectoryAtURL:importDirectory
                  withIntermediateDirectories:YES
                                   attributes:nil
                                        error:&directoryError];
            }

            // Never delete a same-named file before copying. Aside from losing
            // an existing in-flight import, an open-in-place provider can hand
            // back the exact destination URL. A short unique staging name
            // avoids both cases while retaining the extension used to identify
            // PKGs (and not overflowing NAME_MAX for a long provider name).
            NSString *stagedName = NSUUID.UUID.UUIDString;
            if (filename.pathExtension.length)
                stagedName = [stagedName stringByAppendingPathExtension:filename.pathExtension];
            NSURL *destination = [importDirectory URLByAppendingPathComponent:stagedName];

            __block BOOL copied = NO;
            __block NSError *copyError = directoryError;
            if (documents && !directoryError) {
                NSFileCoordinator *coordinator =
                    [[NSFileCoordinator alloc] initWithFilePresenter:nil];
                NSError *coordinationError = nil;
                [coordinator coordinateReadingItemAtURL:url
                                               options:NSFileCoordinatorReadingWithoutChanges
                                                 error:&coordinationError
                                            byAccessor:^(NSURL *coordinatedURL) {
                                                copied = [manager copyItemAtURL:coordinatedURL
                                                                         toURL:destination
                                                                         error:&copyError];
                                            }];
                if (!copyError)
                    copyError = coordinationError;
            }

            if (scoped)
                [url stopAccessingSecurityScopedResource];

            if (!copied) {
                [manager removeItemAtURL:destination error:nil];
                // A common cause is an iCloud-only file whose contents were
                // never downloaded, or insufficient free space for the
                // working copy. Surface the provider's precise failure.
                const char *reason =
                    copyError.localizedDescription.UTF8String ?: "unknown error";
                LOG_ERROR("iOS import copy failed for '{}': {}",
                    filename.UTF8String ?: "?", reason);
                vita3k_ios_report_import_result(
                    std::string("Could not read the selected file: ") + reason
                        + ". If it is stored in iCloud, download it in Files first.",
                    false);
                return;
            }

            NSString *busy = @"Installing game…";
            if (kind == Vita3KIOSFrontendActionKind::ImportFirmware)
                busy = @"Installing firmware…";
            else if (kind == Vita3KIOSFrontendActionKind::ImportLicense)
                busy = @"Installing license…";
            else if (kind == Vita3KIOSFrontendActionKind::ImportSave)
                busy = titleId.length ? @"Importing save…" : @"Importing all game saves...";
            else if (kind == Vita3KIOSFrontendActionKind::ImportLibraryArchive)
                busy = @"Importing games...";

            perform_on_main(^{
                [TsubomiLibraryStateBridge setBusyMessage:busy];
                Vita3KIOSFrontendAction action;
                action.kind = kind;
                action.app_path = destination.path.UTF8String ?: "";
                action.title_id = titleId.UTF8String ?: "";
                queue_action(std::move(action));
            });
        }
    });
}

@end

static Vita3KImportPicker *g_import_picker = nil;

namespace {

UIViewController *document_picker_presenter() {
    UIViewController *presenter = active_window().rootViewController;
    while (presenter.presentedViewController)
        presenter = presenter.presentedViewController;
    return presenter;
}

UIDocumentPickerViewController *import_picker(NSArray<UTType *> *types) {
    // This app consumes imports; it never edits the provider's original file.
    // Explicit copy mode asks Files/File Provider to materialize an app-owned
    // selection instead of relying on an open-in-place security extension.
    // The latter is not reliably forwarded by nested/compatibility containers.
    return [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:types
                                                                      asCopy:YES];
}

// Presents the Files picker for a game/firmware/license import. Attached to the
// + button's UIMenu (games/firmware) and the post-install license prompt.
void present_import_picker(BOOL firmware) {
    UIViewController *presenter = document_picker_presenter();
    if (!presenter)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = firmware ? Vita3KIOSFrontendActionKind::ImportFirmware
                                    : Vita3KIOSFrontendActionKind::ImportGame;
    g_import_picker.titleId = nil;
    NSMutableArray<UTType *> *types = [NSMutableArray array];
    if (firmware) {
        UTType *pup = [UTType typeWithFilenameExtension:@"pup"];
        if (pup)
            [types addObject:pup];
    } else {
        [types addObject:UTTypeZIP];
        UTType *vpk = [UTType typeWithFilenameExtension:@"vpk"];
        if (vpk)
            [types addObject:vpk];
        UTType *pkg = [UTType typeWithFilenameExtension:@"pkg"];
        if (pkg)
            [types addObject:pkg];
    }
    [types addObject:UTTypeData];
    UIDocumentPickerViewController *picker = import_picker(types);
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [presenter presentViewController:picker animated:YES completion:nil];
}

void present_license_picker() {
    UIViewController *presenter = document_picker_presenter();
    if (!presenter)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = Vita3KIOSFrontendActionKind::ImportLicense;
    g_import_picker.titleId = nil;
    // A work.bin has no standard UTType; accept any file.
    UIDocumentPickerViewController *picker = import_picker(@[UTTypeData]);
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [presenter presentViewController:picker animated:YES completion:nil];
}

void present_save_picker(NSString *titleId) {
    UIViewController *presenter = document_picker_presenter();
    if (!presenter)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = Vita3KIOSFrontendActionKind::ImportSave;
    g_import_picker.titleId = titleId;
    UIDocumentPickerViewController *picker = import_picker(@[UTTypeZIP, UTTypeData]);
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [presenter presentViewController:picker animated:YES completion:nil];
}

void present_library_archive_picker() {
    UIViewController *presenter = document_picker_presenter();
    if (!presenter)
        return;
    if (!g_import_picker)
        g_import_picker = [[Vita3KImportPicker alloc] init];
    g_import_picker.kind = Vita3KIOSFrontendActionKind::ImportLibraryArchive;
    g_import_picker.titleId = nil;
    UIDocumentPickerViewController *picker = import_picker(@[UTTypeZIP, UTTypeData]);
    picker.delegate = g_import_picker;
    picker.allowsMultipleSelection = NO;
    [presenter presentViewController:picker animated:YES completion:nil];
}

} // namespace

// Hide or reveal every CAMetalLayer-backed view under the window. The SDL
// drawable keeps the last presented game frame after a session ends, and it
// can bleed into library/settings backgrounds through composition paths that
// don't show up in screenshots. While the library UI is on screen nothing
// renders into it, so hiding it outright is safe.
static void set_metal_drawables_hidden(UIWindow *window, BOOL hidden) {
    if (!window)
        return;
    // Walk the entire window: SDL's drawable normally lives under the root
    // view controller, but a drawable parented to the window itself must be
    // caught too or it keeps showing the last game frame behind settings.
    NSMutableArray<UIView *> *pending = [NSMutableArray arrayWithObject:window];
    while (pending.count) {
        UIView *view = pending.lastObject;
        [pending removeLastObject];
        if ([view.layer isKindOfClass:CAMetalLayer.class]) {
            // Never hide a view the library lives inside: hiding an ancestor
            // hides the library with it and the whole screen goes black.
            if (hidden && library_view() && [library_view() isDescendantOfView:view]) {
                [pending addObjectsFromArray:view.subviews];
                continue;
            }
            view.hidden = hidden;
            continue;
        }
        [pending addObjectsFromArray:view.subviews];
    }
}

void vita3k_ios_show_library(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    const std::vector<Vita3KIOSGameEntry> gamesCopy = games;
    const Vita3KIOSSettings settingsCopy = settings;
    perform_on_main(^{
        UIWindow *window = active_window();
        if (!window)
            return;
        // The library's view goes on the WINDOW, and the controller has NO
        // parent view controller. Both halves of that matter.
        //
        // On the window, because SDL's drawable is the root view controller's
        // view: a library hosted inside it is a descendant of that
        // CAMetalLayer, and set_metal_drawables_hidden must then refuse to
        // hide the layer or it would hide the library too. That layer kept
        // compositing the last frame of a quit game behind the library
        // forever. (The giveaway was that the ghost disappeared during screen
        // recording - capture does not composite a stale Metal drawable.)
        //
        // Without containment, because a child view controller whose view is
        // moved into a window its parent does not own trips UIKit's hierarchy
        // check in _associatedViewControllerForwardsAppearanceCallbacks and
        // raises. Doing both - child of the root controller, view on the
        // window - crashed every launch in 0.27.0. Appearance callbacks are
        // driven manually below instead, which is what SwiftUI's onAppear and
        // task modifiers need.
        UIView *host = window;
        BOOL playLaunchIntro = NO;
        if (!g_library_controller) {
            g_library_controller = [TsubomiLibraryHost libraryViewController];
            [g_library_controller beginAppearanceTransition:YES animated:NO];
            attach_library_view(host);
            [g_library_controller endAppearanceTransition];
            if (!g_app_launch_intro_shown) {
                playLaunchIntro = YES;
                g_app_launch_intro_shown = YES;
            }
        } else if (library_view().superview != host) {
            attach_library_view(host);
        }
        [host layoutIfNeeded];
        library_view().hidden = NO;
        const BOOL animateLaunchIntro = playLaunchIntro && !UIAccessibilityIsReduceMotionEnabled();
        if (animateLaunchIntro) {
            // Cold app launch dropped the library on screen with no
            // transition at all. A short fade + gentle scale-up reads as an
            // intentional entrance instead of the UI just appearing.
            library_view().alpha = 0.0;
            library_view().transform = CGAffineTransformMakeScale(0.96, 0.96);
        }
        publish_core_snapshot(gamesCopy, settingsCopy);
        [TsubomiLibraryStateBridge setJITAvailable:g_jit_available];
        NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
        if (settingsCopy.firmware_ready) {
            // Existing installs that contain the main firmware and fonts never
            // see onboarding, even when upgrading from a build predating it.
            [defaults setBool:YES forKey:@"tsubomi.onboarded"];
            remove_onboarding_view();
        } else if (![defaults boolForKey:@"tsubomi.onboarded"]
            || !settingsCopy.font_package_ready || !settingsCopy.main_firmware_ready) {
            if (!g_onboarding_controller) {
                // Firmware progress reaches the flow through FirmwareState,
                // pushed from the same snapshot above, so there is no
                // equivalent of the old updateFirmwareSettings: call here.
                g_onboarding_controller =
                    [TsubomiOnboardingHost onboardingViewControllerWithFinishHandler:^{
                        void (^removeOnboarding)(void) = ^{
                            remove_onboarding_view();
                        };
                        if (UIAccessibilityIsReduceMotionEnabled()) {
                            removeOnboarding();
                        } else {
                            [UIView animateWithDuration:0.3 animations:^{
                                g_onboarding_controller.view.alpha = 0;
                            } completion:^(__unused BOOL finished) { removeOnboarding(); }];
                        }
                    }];
                // Like the library host, this controller has no UIKit parent.
                // Deliver appearance events so SwiftUI activates its observable
                // subscriptions and onAppear even on iOS 16/17/18.
                [g_onboarding_controller beginAppearanceTransition:YES animated:NO];
                UIView *onboarding = g_onboarding_controller.view;
                onboarding.frame = library_view().bounds;
                onboarding.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
                [library_view() addSubview:onboarding];
                [g_onboarding_controller endAppearanceTransition];
            }
            [library_view() bringSubviewToFront:g_onboarding_controller.view];
        }
        [library_view().superview bringSubviewToFront:library_view()];
        set_metal_drawables_hidden(window, YES);
        [Vita3KPadNavigator.shared start];
        if (animateLaunchIntro) {
            UIView *introTarget = library_view();
            [UIView animateWithDuration:0.5
                                  delay:0.05
                 usingSpringWithDamping:0.86
                  initialSpringVelocity:0.4
                                options:UIViewAnimationOptionCurveEaseOut
                             animations:^{
                introTarget.alpha = 1.0;
                introTarget.transform = CGAffineTransformIdentity;
            }
                             completion:nil];
        }
        // Session teardown may still mutate the view hierarchy after this
        // block (SDL drawable churn); reassert visibility one tick later so a
        // late-added game drawable can't cover or hide the library.
        dispatch_async(dispatch_get_main_queue(), ^{
            if (!g_library_controller)
                return;
            library_view().hidden = NO;
            [library_view().superview bringSubviewToFront:library_view()];
            set_metal_drawables_hidden(library_view().window ?: active_window(), YES);
        });
        // Teardown can still straggle past that one tick, so keep re-hiding on
        // a short timer. Bounded, not forever: teardown straggles for a few
        // hundred ms at most, but the library is the screen the app idles on,
        // so a permanent 4 Hz hierarchy walk was burning wake-ups for the
        // entire time the user sits browsing. Sweep for two seconds, then stop.
        if (!g_library_metal_hide_timer) {
            __block NSInteger sweeps = 8;
            g_library_metal_hide_timer = [NSTimer scheduledTimerWithTimeInterval:0.25
                                                                          repeats:YES
                                                                            block:^(NSTimer *timer) {
                if (!g_library_controller || --sweeps <= 0) {
                    [timer invalidate];
                    g_library_metal_hide_timer = nil;
                    if (g_library_controller)
                        set_metal_drawables_hidden(library_view().window ?: active_window(), YES);
                    return;
                }
                set_metal_drawables_hidden(library_view().window ?: active_window(), YES);
            }];
        }
    });
}

namespace {
std::atomic_bool g_firmware_refresh_requested{ false };
}

void vita3k_ios_request_firmware_refresh() {
    g_firmware_refresh_requested.store(true);
}

bool vita3k_ios_consume_firmware_refresh() {
    return g_firmware_refresh_requested.exchange(false);
}

void vita3k_ios_update_library(const std::vector<Vita3KIOSGameEntry> &games,
    const Vita3KIOSSettings &settings) {
    const std::vector<Vita3KIOSGameEntry> gamesCopy = games;
    const Vita3KIOSSettings settingsCopy = settings;
    perform_on_main(^{
        publish_core_snapshot(gamesCopy, settingsCopy);
    });
}

void vita3k_ios_hide_library() {
    perform_on_main(^{
        [Vita3KPadNavigator.shared stop];
        set_metal_drawables_hidden(library_view().window ?: active_window(), NO);
        remove_onboarding_view();
        // Matches the manual appearance transition in show_library; there is
        // no containment to unwind.
        [g_library_controller beginAppearanceTransition:NO animated:NO];
        [NSLayoutConstraint deactivateConstraints:g_library_constraints ?: @[]];
        g_library_constraints = nil;
        [library_view() removeFromSuperview];
        [g_library_controller endAppearanceTransition];
        g_library_controller = nil;
        [g_library_metal_hide_timer invalidate];
        g_library_metal_hide_timer = nil;
    });
}

std::optional<Vita3KIOSFrontendAction> vita3k_ios_take_frontend_action() {
    const std::lock_guard lock(g_action_mutex);
    auto action = std::move(g_pending_action);
    g_pending_action.reset();
    return action;
}

bool vita3k_ios_logging_enabled() {
    id value = [[NSUserDefaults standardUserDefaults] objectForKey:@"tsubomi.collectLogs"];
    return value == nil || [value boolValue];
}

int vita3k_ios_load_fps_limit() {
    return 60;
}

bool vita3k_ios_consume_double_buffer_default_migration() {
    static NSString *const key = @"tsubomi.doubleBufferDefaultMigrated";
    NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
    if ([defaults boolForKey:key])
        return false;
    [defaults setBool:YES forKey:key];
    return true;
}

void vita3k_ios_present_trophies(const Vita3KIOSTrophyCollection &collection) {
    // Row formatting (grade names, hidden-trophy masking, unlock dates) moved
    // into TsubomiTrophyCollection so the SwiftUI list only lays out strings.
    TsubomiTrophyCollection *bridged = vita3k_ios_internal::bridge_trophies(collection);
    perform_on_main(^{
        [active_window().rootViewController
            presentViewController:[TsubomiTrophyHost trophyViewControllerForCollection:bridged]
                         animated:YES
                       completion:nil];
    });
}

void vita3k_ios_update_trophies(const Vita3KIOSTrophyCollection &collection) {
    TsubomiTrophyCollection *bridged =
        vita3k_ios_internal::bridge_trophies(collection);
    perform_on_main(^{
        [TsubomiTrophyStateBridge updateWithCollection:bridged];
    });
}

// Presents once nothing else is on screen. An export reports its result first,
// and an incomplete one puts up an "Export incomplete" alert - presenting the
// share sheet into that alert while it is still animating means UIKit drops it,
// and the archive the user just waited minutes for is never offered. Waiting
// also reads correctly: dismiss the alert, then choose where the file goes.
static void present_share_when_clear(UIActivityViewController *share, int attempts_left) {
    UIViewController *root = active_window().rootViewController;
    if (!root)
        return;
    if (root.presentedViewController && attempts_left > 0) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.25 * NSEC_PER_SEC)),
            dispatch_get_main_queue(), ^{
                present_share_when_clear(share, attempts_left - 1);
            });
        return;
    }
    UIViewController *presenter = document_picker_presenter();
    if (!presenter)
        return;
    share.popoverPresentationController.sourceView = presenter.view;
    share.popoverPresentationController.sourceRect =
        CGRectMake(CGRectGetMidX(presenter.view.bounds),
            CGRectGetMidY(presenter.view.bounds), 1, 1);
    [presenter presentViewController:share animated:YES completion:nil];
}

void vita3k_ios_share_file(const std::string &path) {
    NSString *filePath = [NSString stringWithUTF8String:path.c_str()];
    perform_on_main(^{
        NSURL *url = [NSURL fileURLWithPath:filePath];
        UIActivityViewController *share = [[UIActivityViewController alloc] initWithActivityItems:@[url] applicationActivities:nil];
        // Two minutes of retries: the user may take a moment to read and
        // dismiss the result alert before the sheet can appear.
        present_share_when_clear(share, 480);
    });
}

static std::string g_log_file_path;

void vita3k_ios_set_log_file_path(const std::string &path) {
    g_log_file_path = path;
}

void vita3k_ios_share_log_file() {
    if (g_log_file_path.empty()) {
        perform_on_main(^{
            present_alert(@"No log yet",
                @"The log file has not been created for this session yet.");
        });
        return;
    }
    vita3k_ios_share_file(g_log_file_path);
}

void vita3k_ios_request_current_trophies() {
    Vita3KIOSFrontendAction action;
    action.kind = Vita3KIOSFrontendActionKind::ShowTrophies;
    queue_action(std::move(action));
}

// The FPS/frametime/graph/RAM/battery readout is SwiftUI now
// (PerformanceOverlayView), fed from vita3k_ios_update_perf_overlay via
// TsubomiPerformanceStateBridge. Only the live-log panel below is still UIKit.

// Optional live log/console overlay (Settings > Performance overlay > Show
// live log): a bottom-docked scrolling panel of the most recent log lines,
// for reporting bugs without pulling the device off to read tsubomi.log.
// Independent of the FPS/frametime/RAM/battery HUD toggles above, so it is
// updated on every vita3k_ios_update_perf_overlay tick regardless of whether
// that HUD itself is shown.
static UIVisualEffectView *g_log_hud = nil;
static UITextView *g_log_text = nil;
// Which material the panel was built with, so a change to the setting rebuilds
// it rather than leaving a glass backdrop up until the next session.
static BOOL g_log_hud_is_glass = YES;
// What the last perf tick put on screen. Read and written only from the
// emulator loop, and only so a tick that has nothing to show can skip the hop
// to the main thread without stranding views that were up a moment ago.
static BOOL g_perf_overlay_shown = NO;
static BOOL g_perf_log_shown = NO;

static void update_log_overlay(UIWindow *window) {
    const BOOL show_log = [NSUserDefaults.standardUserDefaults boolForKey:@"vita3k.perf.log"];
    if (!show_log || !window) {
        g_log_hud.hidden = YES;
        return;
    }
    // The one remaining UIKit surface that sits over a live game, so it follows
    // the same in-game material preference the SwiftUI overlay does: a glass
    // backdrop here is re-sampled on every frame the game draws.
    const BOOL liquid_glass = in_game_liquid_glass_enabled();
    if (g_log_hud && g_log_hud_is_glass != liquid_glass) {
        [g_log_hud removeFromSuperview];
        g_log_hud = nil;
        g_log_text = nil;
    }
    if (!g_log_hud) {
        // Non-interactive: never intercepts the game's touch controls, which
        // stay above it in the window's subview order.
        g_log_hud = [[UIVisualEffectView alloc] initWithEffect:liquid_glass ? glass_effect(NO) : nil];
        g_log_hud_is_glass = liquid_glass;
        if (!liquid_glass)
            g_log_hud.backgroundColor = [UIColor colorWithWhite:0.0 alpha:0.55];
        round_continuous(g_log_hud, 10);
        g_log_hud.clipsToBounds = YES;
        g_log_hud.userInteractionEnabled = NO;
        g_log_text = [[UITextView alloc] init];
        g_log_text.backgroundColor = UIColor.clearColor;
        g_log_text.textColor = [UIColor colorWithWhite:0.85 alpha:1.0];
        g_log_text.font = [UIFont monospacedSystemFontOfSize:9 weight:UIFontWeightRegular];
        g_log_text.editable = NO;
        g_log_text.selectable = NO;
        g_log_text.userInteractionEnabled = NO;
        g_log_text.showsVerticalScrollIndicator = NO;
        g_log_text.textContainerInset = UIEdgeInsetsMake(4, 6, 4, 6);
        [g_log_hud.contentView addSubview:g_log_text];
    }
    if (g_log_hud.superview != window) {
        [window addSubview:g_log_hud];
        [window bringSubviewToFront:g_log_hud];
    }
    g_log_hud.hidden = NO;

    const std::vector<std::string> lines = vita3k_ios_recent_log_lines();
    const size_t shown = std::min<size_t>(lines.size(), 40);
    NSMutableString *joined = [NSMutableString string];
    for (size_t i = lines.size() - shown; i < lines.size(); ++i) {
        [joined appendString:[NSString stringWithUTF8String:lines[i].c_str()] ?: @""];
        [joined appendString:@"\n"];
    }
    g_log_text.text = joined;

    const UIEdgeInsets safe = window.safeAreaInsets;
    const CGFloat windowWidth = CGRectGetWidth(window.bounds);
    const CGFloat windowHeight = CGRectGetHeight(window.bounds);
    const CGFloat width = windowWidth - safe.left - safe.right - 16;
    const CGFloat height = MIN(220.0, windowHeight * 0.32);
    g_log_hud.frame = CGRectMake(safe.left + 8, windowHeight - safe.bottom - height - 8, width, height);
    g_log_text.frame = g_log_hud.bounds;
    if (g_log_text.text.length > 0)
        [g_log_text scrollRangeToVisible:NSMakeRange(g_log_text.text.length - 1, 1)];
}

void vita3k_ios_update_perf_overlay(const float guest_fps, const float frametime_ms) {
    // Memory and battery are sampled here (UIKit side) and pushed, along with
    // the guest FPS and frametime, into the SwiftUI PerformanceState. The
    // readout itself is drawn by PerformanceOverlayView inside the controls
    // overlay - this no longer builds a UIKit HUD. The live-log panel is still
    // UIKit and is updated below.
    const float fps = guest_fps;
    const float ft = frametime_ms;

    // Decide whether there is anything to do *before* hopping threads.
    // NSUserDefaults is thread-safe, and most players run with every metric
    // off: dispatching to the main thread once a second for the whole session
    // just to discover that is a wake-up per second for an overlay nobody
    // enabled. The last state is remembered so the switch-off still gets one
    // final hop to take the views down.
    NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
    const BOOL any = [defaults boolForKey:@"vita3k.perf.fps"]
        || [defaults boolForKey:@"vita3k.perf.frametime"]
        || [defaults boolForKey:@"vita3k.perf.frametimeGraph"]
        || [defaults boolForKey:@"vita3k.perf.ram"]
        || [defaults boolForKey:@"vita3k.perf.battery"];
    const BOOL visible = any && ![defaults boolForKey:@"vita3k.perf.hidden"];
    const BOOL show_log = [defaults boolForKey:@"vita3k.perf.log"];
    if (!visible && !show_log && !g_perf_overlay_shown && !g_perf_log_shown)
        return;
    g_perf_overlay_shown = visible;
    g_perf_log_shown = show_log;

    perform_on_main(^{
        update_log_overlay(active_window());

        [TsubomiPerformanceStateBridge setVisible:visible];
        if (!visible)
            return;

        double memoryMB = 0;
        task_vm_info_data_t vm_info{};
        mach_msg_type_number_t count = TASK_VM_INFO_COUNT;
        if (task_info(mach_task_self(), TASK_VM_INFO,
                reinterpret_cast<task_info_t>(&vm_info), &count) == KERN_SUCCESS)
            memoryMB = vm_info.phys_footprint / (1024.0 * 1024.0);

        UIDevice *device = UIDevice.currentDevice;
        if (!device.batteryMonitoringEnabled)
            device.batteryMonitoringEnabled = YES;
        const float level = device.batteryLevel;
        const NSInteger batteryPercent = level >= 0 ? static_cast<NSInteger>(level * 100.0f + 0.5f) : -1;

        [TsubomiPerformanceStateBridge updateWithFPS:fps
                                           frametime:ft
                                            memoryMB:memoryMB
                                      batteryPercent:batteryPercent];
    });
}

void vita3k_ios_hide_perf_overlay() {
    g_perf_overlay_shown = NO;
    g_perf_log_shown = NO;
    perform_on_main(^{
        [TsubomiPerformanceStateBridge setVisible:NO];
        [g_log_hud removeFromSuperview];
        g_log_hud = nil;
        g_log_text = nil;
    });
}

void vita3k_ios_report_import_result(const std::string &message, const bool success,
    const bool needs_attention) {
    NSString *text = [NSString stringWithUTF8String:message.c_str()] ?: @"Import finished";
    perform_on_main(^{
        [TsubomiLibraryStateBridge setBusyMessage:nil];
        // Onboarding used to render its own inline status for this. The
        // SwiftUI flow instead shows "Installed" from FirmwareState once the
        // package actually lands, and failures still reach the user through
        // the alert below - which is the more accurate signal anyway, since a
        // wrong-package import "succeeds" as a file operation.
        if (success) {
            // An install or license import can make a title's icon appear at a
            // path that was empty when the art cache last read it. Nothing
            // about the entry changes, so drop the cache and force the cells
            // to reload rather than leaving a blank cover until a restart.
            [TsubomiLibraryStateBridge invalidateArt];
            // The toast owns its own dismissal timer in LibraryState.
            [TsubomiLibraryStateBridge showStatusMessage:text];
            const BOOL gameInstalled =
                [text hasPrefix:@"Installed "] || [text localizedCaseInsensitiveContainsString:@"PKG installed"];
            const BOOL licenseInstalled =
                [text localizedCaseInsensitiveContainsString:@"license installed"];
            if (gameInstalled || licenseInstalled)
                [TsubomiSoundEffects playNamed:@"success"];
            if ([text localizedCaseInsensitiveContainsString:@"license"])
                present_alert(@"License installed", text);
            // A toast times out in a few seconds. An archive that is missing a
            // game update is something the user only finds out about when a
            // restore goes wrong months later, so it gets a dialog they have
            // to dismiss.
            if (needs_attention)
                present_alert(@"Export incomplete", text);
        } else {
            if ([text localizedCaseInsensitiveContainsString:@"needs a matching license"]
                || [text localizedCaseInsensitiveContainsString:@"work.bin first"])
                [TsubomiSoundEffects playNamed:@"error"];
            // Keep the precise installer detail on screen until dismissed.
            NSString *title = @"Import failed";
            if ([text localizedCaseInsensitiveContainsString:@"export"])
                title = @"Export failed";
            else if ([text localizedCaseInsensitiveContainsString:@"save"])
                title = @"Save transfer failed";
            present_alert(title, text);
        }
    });
}

void vita3k_ios_report_library_refresh(const bool success) {
    perform_on_main(^{
        [TsubomiLibraryStateBridge reportRefreshSucceeded:success];
    });
}

void vita3k_ios_show_boot_error(const std::string &message) {
    NSString *text = [NSString stringWithUTF8String:message.c_str()] ?: @"The game could not start.";
    perform_on_main(^{
        [TsubomiLibraryStateBridge setBusyMessage:nil];
        present_alert(@"Couldn’t start game", text);
    });
}

void vita3k_ios_set_jit_available(const bool available) {
    perform_on_main(^{
        g_jit_available = available;
        [TsubomiLibraryStateBridge setJITAvailable:available];
    });
}

void vita3k_ios_prompt_license_import(const std::string &title_id) {
    NSString *identifier = [NSString stringWithUTF8String:title_id.c_str()] ?: @"this title";
    perform_on_main(^{
        UIViewController *root = active_window().rootViewController;
        if (!root)
            return;
        UIAlertController *prompt = [UIAlertController
            alertControllerWithTitle:@"License required?"
                             message:[NSString stringWithFormat:@"%@ has no NoNpDrm license installed. If this is a NoNpDrm dump, import its work.bin now.", identifier]
                      preferredStyle:UIAlertControllerStyleAlert];
        [prompt addAction:[UIAlertAction actionWithTitle:@"Import work.bin"
                                                   style:UIAlertActionStyleDefault
                                                 handler:^(__unused UIAlertAction *action) { present_license_picker(); }]];
        [prompt addAction:[UIAlertAction actionWithTitle:@"Not now" style:UIAlertActionStyleCancel handler:nil]];
        [TsubomiSoundEffects playNamed:@"error"];
        [root presentViewController:prompt animated:YES completion:nil];
    });
}

void vita3k_ios_configure_audio_session() {
    NSError *error = nil;
    AVAudioSession *session = AVAudioSession.sharedInstance;
    // Playback so audio keeps running with the mute switch on and the audio
    // unit is actually scheduled; MixWithOthers keeps us polite.
    if (![session setCategory:AVAudioSessionCategoryPlayback
                         mode:AVAudioSessionModeDefault
                      options:AVAudioSessionCategoryOptionMixWithOthers
                        error:&error]) {
        LOG_ERROR("iOS audio session setCategory failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
        error = nil;
    }
    if (![session setPreferredSampleRate:48000 error:&error]) {
        LOG_WARN("iOS audio session preferred sample rate failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
        error = nil;
    }
    constexpr NSTimeInterval preferredBufferDuration = 1024.0 / 48000.0;
    if (![session setPreferredIOBufferDuration:preferredBufferDuration error:&error]) {
        LOG_WARN("iOS audio session preferred buffer duration failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
        error = nil;
    }
    if (![session setActive:YES error:&error]) {
        LOG_ERROR("iOS audio session activation failed: {}",
            error.localizedDescription.UTF8String ?: "unknown");
    } else {
        LOG_INFO("iOS audio session active (Playback), sample rate {} Hz, I/O buffer {:.2f} ms",
            session.sampleRate, session.IOBufferDuration * 1000.0);
    }
}

void vita3k_ios_pump_runloop(const double seconds) {
    // On the main thread (where SDL runs main() on iOS) the run loop owns the
    // UIKit event/timer sources, so running it for `seconds` keeps scrolling,
    // sliders, and glass animations smooth instead of the blind SDL_Delay that
    // starved them. returnAfterSourceHandled:false makes it block the full
    // interval rather than spinning after each event. Off the main thread the
    // run loop has no sources and would return instantly, so sleep instead to
    // avoid a busy loop.
    if (NSThread.isMainThread)
        CFRunLoopRunInMode(kCFRunLoopDefaultMode, seconds, false);
    else
        [NSThread sleepForTimeInterval:seconds];
}

void vita3k_ios_report_settings_result(const std::vector<std::string> &restart_required) {
    NSMutableArray<NSString *> *labels = [NSMutableArray arrayWithCapacity:restart_required.size()];
    for (const auto &label : restart_required)
        [labels addObject:[NSString stringWithUTF8String:label.c_str()]];
    perform_on_main(^{
        [TsubomiSoundEffects playNamed:@"sparkle"];
        if (labels.count == 0)
            return;
        // Restart-required settings are reported through the same toast the
        // library uses for import results, rather than a modal alert: the
        // change has already been applied and saved, so this is information,
        // not a decision.
        [TsubomiLibraryStateBridge showStatusMessage:
            [NSString stringWithFormat:@"Restart Tsubomi to apply: %@",
                [labels componentsJoinedByString:@", "]]];
    });
}
